Repository helbertoro/challenge-html-01, pull requests merged in 2020-02, with the labels that each got.

#1 Created card component
  package-lock.json
  package.json
  src/components/App.jsx
  src/components/Card.jsx
  src/db.js
  src/styles/components/App.styl
  src/styles/components/Card.styl
  src/styles/lib/vars.styl
  webpack.config.js
Labels: enhancement

#2 Grid layout mobile first
  src/components/App.jsx
  src/components/Card.jsx
  src/components/Grid.jsx
  src/db.js
  src/styles/components/App.styl
  src/styles/components/Grid.styl
Labels: enhancement

#3 Created header component
  src/assets/logo.png
  src/components/App.jsx
  src/components/Header.jsx
  src/db.js
  src/icons/BurgerButton.jsx
  src/styles/components/App.styl
  src/styles/components/Header.styl
Labels: enhancement

#4 fixed styles issue
  src/styles/components/Card.styl
  src/styles/components/Grid.styl
Labels: bug

#5 Grid layout Footer
  package-lock.json
  package.json
  src/assets/logo-dark.jpg
  src/assets/redes.jpg
  src/components/App.jsx
  src/components/Footer.jsx
  src/styles/components/Footer.styl
  webpack.config.js
Labels: enhancement

#6 Standardize measures for media queries
  src/db.js
  src/styles/components/Grid.styl
  src/styles/components/Header.styl
  src/styles/lib/vars.styl
Labels: enhancement

#7 Feature/deployment
  .gitignore
  now.json
  package-lock.json
  src/styles/components/Header.styl
Labels: enhancement

#8 Fix/layout
  src/components/Header.jsx
  src/icons/BurgerButton.jsx
  src/styles/components/Card.styl
  src/styles/components/Grid.styl
  src/styles/components/Header.styl
Labels: bug, enhancement
